server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   # Permite rutas dinamicas con Eureka
          lower-case-service-id: true
      routes:
        # === USUARIO SERVICE ===
        - id: usuario-service
          uri: lb://usuario-service
          predicates:
            - Path=/usuario/**

        # === CARRO SERVICE ===
        - id: carro-service
          uri: lb://carro-service
          predicates:
            - Path=/carro/**

        # === MOTO SERVICE ===
        - id: moto-service
          uri: lb://moto-service
          predicates:
            - Path=/moto/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    hostname: localhost

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
